# Admin - root/root; Application - mysqluser/mysqluser
version: '3.3'

services:
  mysql5: # service name, does not matter
    container_name: mysql5
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "test"
      MYSQL_USER: "mysqluser"
      MYSQL_PASSWORD: "mysqluser"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      LANG: C.UTF-8 # fix data import encoding issue, not required here
    volumes: # below folder is with init script for the first time data loading
      - ./docker/mysql5/mysql.cnf:/etc/mysql/conf.d/mysql.utf8.cnf # set utf8 to mysql
